# Generated by Django 5.2.17 on 2026-10-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alumno_apellidos_alter_alumno_disciplina_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='estado',
            field=models.CharField(default='Auditoría Pendiente', max_length=50),
        ),
    ]
