# Generated by Django 5.2.17 on 2026-10-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cierrecaja_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=150)),
                ('operacion', models.CharField(max_length=150)),
                ('modulo', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='Registrado', max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.CharField(max_length=150)),
                ('clase_impartida', models.CharField(max_length=150)),
                ('total_asistentes', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
