# Generated by Django 5.2.17 on 2026-10-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bitacora_registroclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='academia_origen',
            field=models.CharField(default='Kombat', help_text='Ej: Kombat, Iron Kick, Team Mizu', max_length=150),
        ),
        migrations.AddField(
            model_name='alumno',
            name='asociacion',
            field=models.CharField(blank=True, help_text='Ej: WAKO, JJBDP', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='es_competidor',
            field=models.BooleanField(default=False),
        ),
    ]
