# Generated by Django 5.2.17 on 2026-10-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alumno_academia_origen_alumno_asociacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='disciplina_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
