# Generated by Django 5.2.17 on 2026-09-27 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ci_cliente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(blank=True, null=True, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion_zona', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('ci_distribuidor', models.CharField(blank=True, db_column='ci_distribuidor', max_length=20, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('ci_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioProductoAlmacenar',
            fields=[
                ('num_suplementos', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_producto', models.CharField(max_length=50)),
                ('cantidad_almacenada', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario_producto_almacenar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'membresia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanMembresia',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_clases_semana', models.IntegerField()),
            ],
            options={
                'db_table': 'plan_membresia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField()),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('reportado_por', models.ForeignKey(db_column='ci_empleado', on_delete=django.db.models.deletion.CASCADE, to='core_db.empleado')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
